import { Skill } from './classes';

export interface Skills {
  webDevelopment: Skill;
  hybridDevelopment: Skill;
  nativeIosDevelopment: Skill;
  frontEndDevelopment: Skill;
  backEndDevelopment: Skill;
  blockChain: Skill;
  cryptoCurrency: Skill;
  devops: Skill;
  artificialIntelligence: Skill;
  machineLearning: Skill;
  git: Skill;
  github: Skill;
  githubActions: Skill;
  firebase: Skill;
  webrtc: Skill;
  cypress: Skill;
  html: Skill;
  css: Skill;
  sass: Skill;
  js: Skill;
  ts: Skill;
  node: Skill;
  mongo: Skill;
  swift: Skill;
  cpp: Skill;
  java: Skill;
  python: Skill;
  dart: Skill;
  flutter: Skill;
  bootstrap: Skill;
  angular: Skill;
  ionic: Skill;
  cordova: Skill;
  express: Skill;
  electron: Skill;
  capacitor: Skill;
  swiftui: Skill;
  qt: Skill;
}
